AspDotNetTraining/Controllers/AbsoluteController.cs
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace AspDotNetTraining.Controllers
{
    public class AbsoluteController : Controller
    {
        // GET: Absolute
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Store(UploadsCustomViewModel model, HttpPostedFileBase file)
        {
            const string basePath = @"D:\temp\Uploads";

            if (file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);

                if (fileName != null)
                {
                    // Generate a unique GUID for filename
                    fileName = Guid.NewGuid() + Path.GetExtension(fileName);

                    // Create directory if does not already exist
                    Directory.CreateDirectory(basePath);

                    // Save file
                    var filePath = Path.Combine(basePath, fileName);
                    file.SaveAs(filePath);

                    // Map to model - and maybe store in database
                    model.Path = Url.Content(Path.Combine(basePath, fileName));
                }
            }

            return View(model);
        }

        /// <summary>
        /// Display file from file system.
        /// </summary>
        /// <param name="filePath"></param>
        /// <returns></returns>
        public ActionResult Show(string filePath)
        {
            // Maybe perform authorization before serving file

            const string basePath = @"D:\temp\Uploads";

            var fileName = Path.GetFileName(filePath);

            if (fileName == null) return HttpNotFound("File Not Found");

            // Get MIME type
            var mimeType = MimeMapping.GetMimeMapping(fileName);

            var destinationPath = Path.Combine(basePath, fileName);

            return File(destinationPath, mimeType, fileName);
        }
    }
}

AspDotNetTraining/Views/Absolute/Index.cshtml
@model AspDotNetTraining.Controllers.UploadsCustomViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Absolute Path Upload</h2>

@using (Html.BeginForm("Store", "Absolute", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.TextBoxFor(m => m.FileName)

    <input type="file" name="file" id="file" />

    <button type="submit">Upload</button>
}

AspDotNetTraining/Views/Absolute/Store.cshtml
@model AspDotNetTraining.Controllers.UploadsCustomViewModel

@{
    ViewBag.Title = "Absolute File";
}

<h1>Uploaded File to Absolute Path</h1>

<h3>@Model.FileName</h3>

<img src="@Url.Action("Show", new { filePath = Model.Path })" alt="Photo">

@Html.ActionLink("Download File", "Show", new { filePath = Model.Path })