AspDotNetTraining/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspDotNetTraining.Models;
using AspDotNetTraining.Services;
using Dapper;

namespace AspDotNetTraining.Controllers
{
    public class CrudController : Controller
    {
        [HttpPost]
        public ActionResult Delete(int id)
        {
            new StudentService().Delete(id);

            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public ActionResult Update(Student student)
        {
            new StudentService().Update(student);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var student = new StudentService().Find(id);

            return View("Create", student);
        }

        // GET: Crud
        public ActionResult Index()
        {
            var students = new StudentService().GetAll();

            return View(students);
        }

        public ActionResult Create()
        {
            return View(new Student());
        }

        [HttpPost]
        public ActionResult Store(Student student)
        {
            new StudentService().Insert(student);

            return RedirectToAction("Create");
        }
    }
}

AspDotNetTraining/Views/Crud/Create.cshtml
@model AspDotNetTraining.Models.Student
@{
    var isEdit = Model.Id != 0;
    var action = isEdit ? "Update" : "Store";

    ViewBag.Title = "New Student";
}

<h2>
    @(isEdit ? "Edit" : "New") Student
</h2>

@using (Html.BeginForm(action, "Crud"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.IcNumber, "IC Number")
        @Html.TextBoxFor(m => m.IcNumber, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.MatricNumber, "Matric Number")
        @Html.TextBoxFor(m => m.MatricNumber, new { @class = "form-control" })
    </div>

    @Html.HiddenFor(m => m.Id)

    <button type="submit" class="btn btn-primary">Save</button>
}

AspDotNetTraining/Views/Crud/Index.cshtml
@model IEnumerable<AspDotNetTraining.Models.Student>
@{
    ViewBag.Title = "Student List";
}

<h2>Student List</h2>

<table class="table">
    <thead>
    <tr>
        <th>Name</th>
        <th>Matric Number</th>
        <th>IC Number</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var student in @Model)
    {
        <tr>
            <td>
                @Html.ActionLink(student.Name, "Edit", new {id = student.Id})
            </td>
            <td>@student.MatricNumber</td>
            <td>@student.IcNumber</td>
            <td>
                @using (Html.BeginForm("Delete", "Crud", new { id = student.Id }))
                {
                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                }
            </td>
        </tr>
    }
    </tbody>
</table>